### ISSUE TITLE
The client is using an unsupported version of the Socket.IO or Engine.IO protocols

### ISSUE THREAD

**Issue by lufinkey** [juharris/switch-remoteplay#37] opened 2020-12-16 03:38 UTC
When trying to connect to the server from the client, I get the following error:
```
The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
[22:27:30] engineio.server _log_error_once::710 ERROR - The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
```

**Comment by juharris** [comment] 2020-12-16 04:55
Do you think this could be a duplicate of #34? I'll respond there.

**Comment by lufinkey** [comment] 2020-12-16 05:06
Yeah I managed to get this to work locally but updating the
socket.io-client dependency to 3.0.4

**Comment by juharris** [comment] 2020-12-16 16:39
That's great to hear! I'll test it out myself in a few days and use specific version numbers in setup.py/package.json. Sorry about this.

**Comment by lufinkey** [comment] 2020-12-16 17:21
@juharris no problem! Thanks for putting this tool together!

**Comment by lufinkey** [comment] 2020-12-16 17:21
If you have a kofi or anything like that, let me know and I'll definitely throw you some money

**Closed** 2020-12-19 02:37 UTC
Labels: bug

**Comment by juharris** [comment] 2020-12-19 02:41
That's very kind of you! Perhaps you can just make a donation to something and think of me? Something environmental/STEM related that helps young students/women/disadvantaged people.
